# Generated by Django 4.2.6 on 2024-04-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='annee',
            field=models.CharField(default=2024, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(default='etudiant', max_length=255),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(default='etudiant', max_length=255),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='semestre',
            field=models.CharField(default='s2', max_length=255),
        ),
        migrations.AddField(
            model_name='orientation',
            name='semestre',
            field=models.CharField(default='s2', max_length=255),
        ),
        migrations.AddField(
            model_name='orientation',
            name='tiltre',
            field=models.CharField(default='choix', max_length=255),
        ),
    ]
