# Generated by Django 4.2.6 on 2024-06-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridEvaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('critere1', models.CharField(max_length=255)),
                ('critere2', models.CharField(max_length=255)),
                ('critere3', models.CharField(max_length=255)),
                ('critere4', models.CharField(max_length=255)),
                ('critere5', models.CharField(max_length=255)),
                ('critere6', models.CharField(max_length=255)),
                ('critere7', models.CharField(max_length=255)),
                ('annee', models.IntegerField()),
            ],
        ),
    ]
