# Generated by Django 4.2.7 on 2024-04-20 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.IntegerField()),
                ('choix1', models.CharField(choices=[('dsi', 'DSI'), ('rss', 'RSS'), ('cnm', 'CNM')], max_length=20)),
                ('choix2', models.CharField(choices=[('dsi', 'DSI'), ('rss', 'RSS'), ('cnm', 'CNM')], max_length=20)),
                ('choix3', models.CharField(choices=[('dsi', 'DSI'), ('rss', 'RSS'), ('cnm', 'CNM')], max_length=20)),
                ('idU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.customuser')),
            ],
        ),
    ]
