# Generated by Django 4.2.6 on 2024-06-21 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_gridevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='choix_filiere',
            name='idc',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='projet.orientation'),
            preserve_default=False,
        ),
    ]
