# Generated by Django 4.2.7 on 2024-04-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_demande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('idE', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
