# Generated by Django 4.2.6 on 2024-04-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_choix_filiere_delete_demande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choix_filiere',
            name='choix1',
            field=models.CharField(choices=[('DSI', 'DSI'), ('RSS', 'RSS'), ('CNM', 'CNM')], max_length=20),
        ),
        migrations.AlterField(
            model_name='choix_filiere',
            name='choix2',
            field=models.CharField(choices=[('DSI', 'DSI'), ('RSS', 'RSS'), ('CNM', 'CNM')], max_length=20),
        ),
        migrations.AlterField(
            model_name='choix_filiere',
            name='choix3',
            field=models.CharField(choices=[('DSI', 'DSI'), ('RSS', 'RSS'), ('CNM', 'CNM')], max_length=20),
        ),
    ]
