# Generated by Django 4.2.6 on 2024-06-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_choix_filiere_idc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choix_filiere',
            name='idc',
        ),
    ]
