# Generated by Django 4.2.6 on 2024-04-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_orientation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orientation',
            old_name='tiltre',
            new_name='titre',
        ),
    ]
