# Generated by Django 4.2.6 on 2024-06-21 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0004_remove_choix_filiere_idc'),
    ]

    operations = [
        migrations.AddField(
            model_name='choix_filiere',
            name='idc',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='projet.orientation'),
            preserve_default=False,
        ),
    ]
