# Generated by Django 4.2.7 on 2024-04-21 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0005_orientation_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientation',
            name='idu',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='projet.customuser'),
            preserve_default=False,
        ),
    ]
