# Generated by Django 4.2.6 on 2024-06-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0005_choix_filiere_idc'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientation_f',
            name='idO',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, to='projet.orientation'),
            preserve_default=False,
        ),
    ]
